//! `#[rate_limit(rps = N, burst = N)]` decorator.
//!
//! Wraps a function body in a token-bucket rate limiter. The first
//! `burst` calls proceed immediately; subsequent calls are throttled
//! to `rps` per second, computed from the elapsed time since the
//! last refill.
//!
//! ## Implementation
//!
//! Two static atomics per decorated function store the bucket state:
//!
//! - `__RL_TOKENS` — current available tokens (capped at `burst`).
//! - `__RL_LAST_NS` — wall-clock time (ns since UNIX_EPOCH) of the
//!   last refill.
//!
//! Each call computes the time elapsed since `__RL_LAST_NS`, adds
//! `elapsed / interval` tokens (capped at `burst`), and either
//! atomically consumes a token or sleeps until the next one is
//! available. The compare-exchange loop is the standard lock-free
//! pattern; the only contention is a single 32-bit CAS per call.
//!
//! The `AsyncExecutor` registered with `tokitai_core` (if any) is
//! used to drive the sleep on async functions so we do not block a
//! runtime worker thread.
//!
//! ## v2 composition note
//!
//! A `governor`-style implementation would be cleaner, but to keep
//! zero new dependencies we hand-roll the atomic dance here. For
//! nested `#[rate_limit]`s, a per-function `__RL_*` static is the
//! right granularity — the per-method statics generated by this
//! macro do not collide.

use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{parse2, ItemFn, LitInt};

/// Parsed `#[rate_limit(...)]` argument list.
#[derive(Debug, Clone)]
pub struct RateLimitArgs {
    pub rps: u32,
    pub burst: u32,
}

impl syn::parse::Parse for RateLimitArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let mut rps: u32 = 1;
        let mut burst: u32 = 1;
        while !input.is_empty() {
            let key: syn::Ident = input.parse()?;
            input.parse::<syn::token::Eq>()?;
            match key.to_string().as_str() {
                "rps" => {
                    let v: LitInt = input.parse()?;
                    rps = v.base10_parse()?;
                }
                "burst" => {
                    let v: LitInt = input.parse()?;
                    burst = v.base10_parse()?;
                }
                _ => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!("unknown #[rate_limit] arg: {}", key),
                    ));
                }
            }
            if input.peek(syn::token::Comma) {
                let _: syn::token::Comma = input.parse()?;
            }
        }
        Ok(RateLimitArgs { rps, burst })
    }
}

/// Expand `#[rate_limit(args)] fn ...` into a function whose body is
/// preceded by a token-bucket guard. The function signature is
/// preserved.
pub fn expand(args: TokenStream2, input: TokenStream2) -> TokenStream2 {
    let parsed = match syn::parse2::<RateLimitArgs>(args) {
        Ok(a) => a,
        Err(e) => return e.to_compile_error(),
    };
    let mut func: ItemFn = match parse2::<ItemFn>(input) {
        Ok(f) => f,
        Err(e) => return e.to_compile_error(),
    };

    let rps = parsed.rps.max(1);
    let burst = parsed.burst.max(1);
    // 1e9 ns / rps. For rps=0 we already clamped to 1.
    let interval_ns: u64 = 1_000_000_000u64 / rps as u64;
    let is_async = func.sig.asyncness.is_some();
    let original_block = func.block.clone();

    // The guard:
    //   1. Snapshot the wall clock and the static state.
    //   2. Compute refill = elapsed / interval (capped at burst).
    //   3. If tokens > 0, CAS-decrement and proceed.
    //   4. Otherwise sleep for (interval - elapsed % interval) ns
    //      (driven through the AsyncExecutor for async) and retry.
    let guard: TokenStream2 = quote! {{
        static __RL_TOKENS: ::std::sync::atomic::AtomicU32 =
            ::std::sync::atomic::AtomicU32::new(#burst);
        static __RL_LAST_NS: ::std::sync::atomic::AtomicU64 =
            ::std::sync::atomic::AtomicU64::new(0u64);
        use ::std::sync::atomic::Ordering;

        let __rl_interval_ns: u64 = #interval_ns;
        let __rl_burst: u32 = #burst;
        'rate_limit_loop: loop {
            let __rl_now_ns: u64 = ::std::time::SystemTime::now()
                .duration_since(::std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos() as u64)
                .unwrap_or(0u64);
            let __rl_last_ns: u64 = __RL_LAST_NS.load(Ordering::Relaxed);
            let __rl_tokens: u32 = __RL_TOKENS.load(Ordering::Relaxed);
            let __rl_elapsed: u64 = __rl_now_ns.saturating_sub(__rl_last_ns);
            let __rl_refill: u32 = (__rl_elapsed / __rl_interval_ns) as u32;
            let __rl_new_tokens: u32 =
                if (__rl_tokens as u64) + (__rl_refill as u64) > __rl_burst as u64 {
                    __rl_burst
                } else {
                    __rl_tokens + __rl_refill
                };
            if __rl_new_tokens > 0u32 {
                if __RL_TOKENS
                    .compare_exchange(
                        __rl_tokens,
                        __rl_new_tokens - 1u32,
                        Ordering::Relaxed,
                        Ordering::Relaxed,
                    )
                    .is_ok()
                {
                    if __rl_refill > 0u32 {
                        __RL_LAST_NS.store(__rl_now_ns, Ordering::Relaxed);
                    }
                    break 'rate_limit_loop;
                }
            } else {
                let __rl_wait_ns: u64 =
                    __rl_interval_ns - (__rl_elapsed % __rl_interval_ns);
                if #is_async {
                    // T-004: drive the wait through the runtime's
                    // executor via `tokitai_core::async_sleep`, which
                    // returns a future that yields to the executor
                    // for the full wait duration instead of
                    // blocking the worker thread.
                    ::tokitai_core::async_sleep(
                        ::std::time::Duration::from_nanos(__rl_wait_ns),
                    ).await;
                } else {
                    ::std::thread::sleep(
                        ::std::time::Duration::from_nanos(__rl_wait_ns),
                    );
                }
            }
        }
    }};

    let new_block: TokenStream2 = if is_async {
        quote! {{
            #guard
            let __rl_result = async move #original_block;
            __rl_result.await
        }}
    } else {
        quote! {{
            #guard
            #original_block
        }}
    };

    func.block = match syn::parse2::<Box<syn::Block>>(new_block) {
        Ok(b) => b,
        Err(e) => return e.to_compile_error(),
    };

    quote! { #func }
}
