//! Build script for `tokitai-mcp-server`.
//!
//! Two responsibilities:
//!
//! 1. **T-024 cross-crate version manifest.** Emit a generated
//!    source file under `OUT_DIR` that re-exports the version of
//!    `tokitai-core` the server crate was compiled against. The
//!    generated file declares a `pub const TOKITAI_VERSION: &str`
//!    populated from `env!("CARGO_PKG_VERSION")` of the
//!    `tokitai-core` crate — the version is read by the runtime
//!    `serve()` entry point via `include!` and is compared against
//!    the `--require-tokitai=<prefix>` CLI flag. The manifest is
//!    build-script-emitted (not a plain `pub const`) so the value
//!    is anchored to the resolved version at compile time and
//!    cannot drift silently.
//!
//! 2. **Tokitai compile-env forwarding (T-015 family).** Keep the
//!    proc-macro aware of the consumer's `TOKITAI_QUIET` and
//!    `TOKITAI_PROFILE` settings so per-impl-block profiling and
//!    warn-suppression keep working unchanged. This block mirrors
//!    the env-var forwarding the user-facing `tokitai` crate's
//!    build script already does; we duplicate the forwarding here
//!    so a consumer who depends on `tokitai-mcp-server` directly
//!    (without going through `tokitai`) still benefits.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // ----------------------------------------------------------------
    // T-024: emit the cross-crate version manifest.
    //
    // We pin the constant to the version of the `tokitai-core`
    // crate Cargo resolved for this build.
    //
    // Resolution strategy: we read `CARGO_PKG_VERSION` of
    // tokitai-core by parsing the `Cargo.lock` file Cargo writes
    // next to our `Cargo.toml`. The lockfile is the canonical
    // source of resolved versions and is the only file that
    // contains a direct-dep version string for an indirect or
    // workspace-internal crate. We do not use the `links` /
    // `DEP_*_VERSION` mechanism because that requires the linked
    // crate to declare `links = "..."`, which can only be
    // claimed by ONE crate in the dep graph; we want the slot
    // free for future use. Parsing the lockfile is a small,
    // std-only scan and stays inside the no-new-deps hard rule.
    //
    // The parsed version is then embedded in a generated source
    // file under `OUT_DIR/tokitai_manifest.rs`; the runtime
    // `serve()` function reads the constant via `include!`.
    // ----------------------------------------------------------------
    let core_version = resolve_tokitai_core_version();

    let manifest = format!(
        "// AUTO-GENERATED by tokitai-mcp-server/build.rs (T-024).\n\
         // DO NOT EDIT — this file is regenerated on every build.\n\
         //\n\
         // Re-export of the `tokitai-core` version this crate was\n\
         // compiled against. The runtime `serve()` entry point\n\
         // compares this constant against the `--require-tokitai=<prefix>`\n\
         // CLI flag so cross-crate drift is rejected at startup.\n\
         pub const TOKITAI_VERSION: &str = {:?};\n\
         ",
        core_version
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by Cargo");
    let out_path = Path::new(&out_dir).join("tokitai_manifest.rs");
    fs::write(&out_path, manifest).expect("write tokitai_manifest.rs");

    // Force a rebuild when the `Cargo.lock` changes (the
    // tokitai-core version is sourced from it) or when the
    // user sets a version override.
    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        let lock_path = Path::new(&manifest_dir).join("../Cargo.lock");
        println!("cargo:rerun-if-changed={}", lock_path.display());
    }
    println!("cargo:rerun-if-env-changed=TOKITAI_VERSION_OVERRIDE");

    // Allow operators to override the manifest at build time (e.g.
    // for canary / staging deploys). The override is a literal
    // SemVer string. When unset, the manifest carries the
    // resolved version of `tokitai-core`.
    if let Ok(override_v) = env::var("TOKITAI_VERSION_OVERRIDE") {
        if !override_v.is_empty() {
            let manifest_override = format!(
                "// AUTO-GENERATED by tokitai-mcp-server/build.rs (T-024).\n\
                 // DO NOT EDIT — this file is regenerated on every build.\n\
                 //\n\
                 // Override path: TOKITAI_VERSION_OVERRIDE was set at\n\
                 // build time. The runtime `serve()` entry point will\n\
                 // use this literal instead of the resolved\n\
                 // `tokitai-core` version.\n\
                 pub const TOKITAI_VERSION: &str = {:?};\n\
                 ",
                override_v
            );
            fs::write(&out_path, manifest_override)
                .expect("write tokitai_manifest.rs (override path)");
        }
    }

    // ----------------------------------------------------------------
    // Tokitai compile-env forwarding (T-015 family).
    //
    // Forward the macro's per-impl-block knobs (TOKITAI_QUIET,
    // TOKITAI_PROFILE, TOKITAI_PROFILE_BUDGET) when the consumer
    // crate has set them in its environment. This is the same
    // pattern `tokitai-macros/build.rs` and `tokitai/build.rs`
    // use; we re-emit them here so a consumer that depends on
    // `tokitai-mcp-server` directly still benefits. Consumers that
    // depend on `tokitai` first get the same env vars via
    // `tokitai`'s build script — the duplicate forwarding is
    // idempotent (last-write-wins per `cargo:rustc-env=`).
    // ----------------------------------------------------------------
    println!("cargo:rustc-env=TOKITAI_QUIET=1");

    if let Ok(value) = env::var("TOKITAI_PROFILE") {
        if !value.is_empty() {
            println!("cargo:rustc-env=TOKITAI_PROFILE={}", value);
        }
    }

    if let Ok(value) = env::var("TOKITAI_PROFILE_BUDGET") {
        if !value.is_empty() {
            println!("cargo:rustc-env=TOKITAI_PROFILE_BUDGET={}", value);
        }
    }

    // Re-run on env-var changes for the forwarded flags.
    println!("cargo:rerun-if-env-changed=TOKITAI_QUIET");
    println!("cargo:rerun-if-env-changed=TOKITAI_PROFILE");
    println!("cargo:rerun-if-env-changed=TOKITAI_PROFILE_BUDGET");
}

/// Resolve the version of the `tokitai-core` crate from the
/// workspace `Cargo.lock` file. Returns an empty `String` when
/// the entry is not found (the runtime refuses to start in that
/// case).
///
/// Cargo.lock entries look like:
///
/// ```text
/// [[package]]
/// name = "tokitai-core"
/// version = "0.5.1"
/// ```
///
/// We scan the file linearly for the first `name = "tokitai-core"`
/// line and read the next `version = "..."` line. A linear scan
/// is the right shape: `Cargo.lock` is small (a few KB) and the
/// cost of a regex engine is not worth it.
fn resolve_tokitai_core_version() -> String {
    // `CARGO_MANIFEST_DIR` points at the directory of the
    // mcp-server crate. The workspace `Cargo.lock` lives at the
    // workspace root, which is one level up.
    let manifest_dir = match env::var("CARGO_MANIFEST_DIR") {
        Ok(d) => d,
        Err(_) => return String::new(),
    };
    let lock_path = Path::new(&manifest_dir).join("../Cargo.lock");
    let content = match fs::read_to_string(&lock_path) {
        Ok(c) => c,
        Err(_) => return String::new(),
    };
    let mut in_tokitai_core = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("name ") && trimmed.contains("\"tokitai-core\"") {
            in_tokitai_core = true;
            continue;
        }
        if in_tokitai_core && trimmed.starts_with("version ") {
            // Parse `version = "0.5.1"`. The lockfile format
            // is deterministic, so a single `=` is the only
            // separator.
            if let Some(rest) = trimmed.strip_prefix("version") {
                if let Some(rest) = rest.trim().strip_prefix('=') {
                    let v = rest.trim().trim_matches('"');
                    return v.to_string();
                }
            }
        }
        // End of the package block: `[[package]]` re-opens, and
        // any other top-level key (e.g. `dependencies`) closes
        // the block.
        if in_tokitai_core && trimmed.starts_with('[') {
            break;
        }
    }
    String::new()
}
