//! Build script for `tokitai-mcp-server`.
//!
//! Two responsibilities:
//!
//! 1. **T-024 cross-crate version manifest.** Emit a generated
//!    source file under `OUT_DIR` that re-exports the version of
//!    `tokitai-core` the server crate was compiled against. The
//!    generated file declares a `pub const TOKITAI_VERSION: &str`
//!    populated from the workspace `Cargo.lock`. The version is
//!    read by the runtime `serve()` entry point via `include!`
//!    and is compared against the `--require-tokitai=<prefix>`
//!    CLI flag. The manifest is build-script-emitted (not a plain
//!    `pub const`) so the value is anchored to the resolved
//!    version at compile time and cannot drift silently.
//!
//!    The lockfile is resolved by walking upward from
//!    `CARGO_MANIFEST_DIR` looking for a `Cargo.toml` that
//!    declares `[workspace]`. This handles non-standard build
//!    layouts (vendored deps, `cargo subcrate` crates nested
//!    under `crates/foo/`, etc.).  When resolution fails, a
//!    `cargo:warning=` is emitted and the manifest carries the
//!    sentinel version `0.0.0-unresolved` so the runtime
//!    refusal trips loudly.
//!
//!    `TOKITAI_VERSION_OVERRIDE` was removed in M-0.9.1 as a
//!    security-hardening measure (it silently forged the
//!    manifest and defeated the cross-crate assertion).  The env
//!    var is still checked so we emit a `cargo:warning=` when
//!    someone has it set, but it no longer has any effect.
//!
//! 2. **Tokitai compile-env forwarding (T-015 family).** Keep the
//!    proc-macro aware of the consumer's `TOKITAI_QUIET` and
//!    `TOKITAI_PROFILE` settings so per-impl-block profiling and
//!    warn-suppression keep working unchanged. This block mirrors
//!    the env-var forwarding the user-facing `tokitai` crate's
//!    build script already does; we duplicate the forwarding here
//!    so a consumer who depends on `tokitai-mcp-server` directly
//!    (without going through `tokitai`) still benefits.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // ----------------------------------------------------------------
    // T-024: emit the cross-crate version manifest.
    //
    // We pin the constant to the version of the `tokitai-core`
    // crate Cargo resolved for this build.
    //
    // Resolution strategy: we read the version of `tokitai-core`
    // by parsing the workspace `Cargo.lock`.  The lockfile is the
    // canonical source of resolved versions and is the only file
    // that contains a direct-dep version string for an indirect or
    // workspace-internal crate.  We do not use the `links` /
    // `DEP_*_VERSION` mechanism because that requires the linked
    // crate to declare `links = "..."`, which can only be
    // claimed by ONE crate in the dep graph; we want the slot
    // free for future use.  Parsing the lockfile is a small,
    // std-only scan and stays inside the no-new-deps hard rule.
    //
    // We find the lockfile by walking upward from manifest_dir
    // looking for a Cargo.toml with `[workspace]`; this handles
    // non-standard layouts (vendored deps, crates under
    // `crates/foo/`, etc.).  When resolution fails the manifest
    // carries `0.0.0-unresolved` and the runtime refuses to
    // start (unless `--allow-tokitai-mismatch` is set).
    // ----------------------------------------------------------------
    let core_version = resolve_tokitai_core_version();

    // Emit the manifest.  When resolution failed the runtime
    // will refuse to start unless `--allow-tokitai-mismatch`
    // is set, so a loud warning at build time is appropriate.
    let sentinel = core_version.is_empty() || core_version == "0.0.0-unresolved";
    if sentinel {
        println!(
            "cargo:warning=tokitai-mcp-server: could not resolve tokitai-core \
             version from workspace Cargo.lock; manifest carries \
             \"0.0.0-unresolved\" and the server will refuse to start \
             without --allow-tokitai-mismatch.  Check that the workspace \
             Cargo.lock exists and contains a [[package]] entry for \
             tokitai-core."
        );
    }

    let version_to_write = if core_version.is_empty() {
        "0.0.0-unresolved".to_string()
    } else {
        core_version
    };

    let manifest = format!(
        "// AUTO-GENERATED by tokitai-mcp-server/build.rs (T-024).\n\
         // DO NOT EDIT — this file is regenerated on every build.\n\
         //\n\
         // Re-export of the `tokitai-core` version this crate was\n\
         // compiled against. The runtime `serve()` entry point\n\
         // compares this constant against the `--require-tokitai=<prefix>`\n\
         // CLI flag so cross-crate drift is rejected at startup.\n\
         pub const TOKITAI_VERSION: &str = {:?};\n\
         ",
        version_to_write
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by Cargo");
    let out_path = Path::new(&out_dir).join("tokitai_manifest.rs");
    fs::write(&out_path, manifest).expect("write tokitai_manifest.rs");

    // Register rebuild triggers.
    // The workspace Cargo.lock — when the tokitai-core version
    // changes the manifest must be regenerated.
    if let Ok(manifest_dir) = env::var("CARGO_MANIFEST_DIR") {
        if let Some(root) = find_workspace_root(Path::new(&manifest_dir)) {
            let lock_path = root.join("Cargo.lock");
            println!("cargo:rerun-if-changed={}", lock_path.display());
            // Also watch the workspace Cargo.toml — if a
            // non-workspace layout becomes a workspace build
            // (e.g. vendored → normal) the root changes.
            let ws_toml = root.join("Cargo.toml");
            println!("cargo:rerun-if-changed={}", ws_toml.display());
        }
    }

    // TOKITAI_VERSION_OVERRIDE was removed in M-0.9.1 as a
    // security-hardening measure.  The env var is still checked so
    // we can emit a clear warning when someone has it set, but it
    // no longer has any effect on the generated manifest.  Canary
    // / staging deploys should use a release branch instead.
    if let Some(override_v) = env::var("TOKITAI_VERSION_OVERRIDE")
        .ok()
        .filter(|v| !v.is_empty())
    {
        println!(
            "cargo:warning=TOKITAI_VERSION_OVERRIDE={:?} is set but no longer \
             supported (removed in M-0.9.1).  Canary / staging deploys must \
             use a release branch.  See docs/API_STABILITY.md.",
            override_v
        );
    }

    // ----------------------------------------------------------------
    // Tokitai compile-env forwarding (T-015 family).
    //
    // Forward the macro's per-impl-block knobs (TOKITAI_QUIET,
    // TOKITAI_PROFILE, TOKITAI_PROFILE_BUDGET) when the consumer
    // crate has set them in its environment. This is the same
    // pattern `tokitai-macros/build.rs` and `tokitai/build.rs`
    // use; we re-emit them here so a consumer that depends on
    // `tokitai-mcp-server` directly still benefits. Consumers that
    // depend on `tokitai` first get the same env vars via
    // `tokitai`'s build script — the duplicate forwarding is
    // idempotent (last-write-wins per `cargo:rustc-env=`).
    // ----------------------------------------------------------------
    println!("cargo:rustc-env=TOKITAI_QUIET=1");

    if let Ok(value) = env::var("TOKITAI_PROFILE") {
        if !value.is_empty() {
            println!("cargo:rustc-env=TOKITAI_PROFILE={}", value);
        }
    }

    if let Ok(value) = env::var("TOKITAI_PROFILE_BUDGET") {
        if !value.is_empty() {
            println!("cargo:rustc-env=TOKITAI_PROFILE_BUDGET={}", value);
        }
    }

    // Re-run on env-var changes for the forwarded flags.
    println!("cargo:rerun-if-env-changed=TOKITAI_QUIET");
    println!("cargo:rerun-if-env-changed=TOKITAI_PROFILE");
    println!("cargo:rerun-if-env-changed=TOKITAI_PROFILE_BUDGET");
}

/// Walk upward from `crate_dir` looking for a `Cargo.toml` that
/// declares `[workspace]`.  Returns the directory containing that
/// `Cargo.toml`, or `None` if no workspace root is found.
fn find_workspace_root(crate_dir: &Path) -> Option<std::path::PathBuf> {
    let mut current = Some(crate_dir);
    while let Some(dir) = current {
        let candidate = dir.join("Cargo.toml");
        if let Ok(content) = fs::read_to_string(&candidate) {
            if content.lines().any(|l| l.trim() == "[workspace]") {
                return Some(dir.to_path_buf());
            }
        }
        current = dir.parent();
    }
    None
}

/// Resolve the version of the `tokitai-core` crate from the
/// workspace `Cargo.lock` file.  Returns an empty `String` when
/// the entry is not found (the runtime refuses to start in that
/// case, unless `--allow-tokitai-mismatch` is set).
///
/// The lockfile is located by walking upward from
/// `CARGO_MANIFEST_DIR` to find the workspace root (a
/// `Cargo.toml` with `[workspace]`).
///
/// Cargo.lock entries look like:
///
/// ```text
/// [[package]]
/// name = "tokitai-core"
/// version = "0.5.1"
/// ```
///
/// We scan the file linearly for the first `name = "tokitai-core"`
/// line and read the next `version = "..."` line. A linear scan
/// is the right shape: `Cargo.lock` is small (a few KB) and the
/// cost of a regex engine is not worth it.
fn resolve_tokitai_core_version() -> String {
    let manifest_dir = match env::var("CARGO_MANIFEST_DIR") {
        Ok(d) => d,
        Err(_) => return String::new(),
    };
    let root = match find_workspace_root(Path::new(&manifest_dir)) {
        Some(r) => r,
        None => return String::new(),
    };
    let lock_path = root.join("Cargo.lock");
    let content = match fs::read_to_string(&lock_path) {
        Ok(c) => c,
        Err(_) => return String::new(),
    };
    let mut in_tokitai_core = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("name ") && trimmed.contains("\"tokitai-core\"") {
            in_tokitai_core = true;
            continue;
        }
        if in_tokitai_core && trimmed.starts_with("version ") {
            if let Some(rest) = trimmed.strip_prefix("version") {
                if let Some(rest) = rest.trim().strip_prefix('=') {
                    let v = rest.trim().trim_matches('"');
                    return v.to_string();
                }
            }
        }
        if in_tokitai_core && trimmed.starts_with('[') {
            break;
        }
    }
    String::new()
}
