//! Compile-time lookup of every operation in the parsed OpenAPI spec.
//!
//! Emits a `pub static OPENAPI_OPS: ::phf::Map<&'static str,
//! OpenApiOp> = ...;` that callers can introspect at runtime — e.g. to
//! list every tool the macro would have generated, or to print a
//! summary table. The map is built with `phf::phf_map!` so lookup is
//! fully deterministic and zero-cost.
//!
//! `OpenApiOp` is a small generated struct (one per impl block) that
//! carries the bits of OpenAPI metadata the macro keeps around: the
//! HTTP method, the path template, the JSON input schema, and a
//! short description.

use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};

use super::parser::OpenApiSpec;

/// Render the `pub static OPENAPI_OPS: ::phf::Map<...>` and the
/// `OpenApiOp` struct definition.
pub fn generate_spec_static(
    impl_name: &syn::Ident,
    spec: &OpenApiSpec,
    spec_path: &str,
) -> TokenStream2 {
    let static_name = format_ident!("__OPENAPI_OPS_{}", impl_name);
    let op_struct_name = format_ident!("__OpenApiOp_{}", impl_name);

    // The static name embeds the impl block's type name verbatim, so it
    // may not satisfy Rust's SCREAMING_SNAKE_CASE convention when the type
    // name is PascalCase (e.g. `OpenApiClient`). Allow the generated
    // identifier on the static itself; it remains unique per impl block.
    let static_allow_attr = quote! { #[allow(non_upper_case_globals)] };

    // Build the phf entries. We key by `operation_id` (or fall back to
    // a synthetic `METHOD /path` key when the spec omits the field).
    let mut entries: Vec<TokenStream2> = Vec::new();
    for (path, method, op) in spec.all_operations() {
        let key = op
            .operation_id
            .clone()
            .unwrap_or_else(|| format!("{} {}", method, path));
        let http_method = method.to_string();
        let path_t = path.to_string();
        let description = op.description_or_summary();
        let input_schema = op.input_schema().to_string();

        entries.push(quote! {
            #key => #op_struct_name {
                operation_id: #key,
                http_method: #http_method,
                path: #path_t,
                description: #description,
                input_schema: #input_schema,
            }
        });
    }

    // The struct definition uses `&'static str` for all fields, so the
    // whole phf map can live in a const context.
    let struct_def = quote! {
        /// Operation metadata for every entry in the OpenAPI spec.
        ///
        /// Generated by the `#[openapi(...)]` macro. Field order is
        /// stable across runs of the same spec.
        #[doc(hidden)]
        #[derive(Debug, Clone)]
        #[allow(non_camel_case_types)]
        pub struct #op_struct_name {
            /// The `operationId` (or `METHOD /path` fallback).
            pub operation_id: &'static str,
            /// HTTP method (`"GET"`, `"POST"`, ...).
            pub http_method: &'static str,
            /// Path template (e.g. `/v1/chat/completions`).
            pub path: &'static str,
            /// Short description or summary from the spec.
            pub description: &'static str,
            /// JSON input schema derived from the operation.
            pub input_schema: &'static str,
        }
    };

    // The static itself. We also expose the raw spec text via
    // `OPENAPI_SPEC_RAW` so callers can re-parse it at runtime if
    // they need to (e.g. for `$ref` resolution).
    let spec_path_lit = spec_path.to_string();

    let static_def = quote! {
        /// The raw OpenAPI spec, embedded at compile time.
        pub static __OPENAPI_SPEC_RAW: &'static str = include_str!(#spec_path_lit);

        /// Lookup table from `operationId` to operation metadata.
        #static_allow_attr
        pub static #static_name: ::phf::Map<
            &'static str,
            #op_struct_name,
        > = ::phf::phf_map! {
            #(#entries),*
        };
    };

    quote! {
        #struct_def
        #static_def
    }
}
