//! Advanced type support example
//!
//! Demonstrates Tokitai's support for complex types:
//! - Nested `Option` types
//! - `Vec` element types
//! - `HashMap`
//! - Parameter doc-comment extraction
//! - Parameter attributes (validation, transformation, aliases)
//!
//! Run with: `cargo run --example advanced_types`

use std::collections::HashMap;
use tokitai::tool;
use tokitai::ToolProvider;

/// Advanced tool services
pub struct AdvancedTools;

#[tool]
impl AdvancedTools {
    /// Process user information
    ///
    /// Supports optional parameters and complex types
    ///
    /// - `user_id`: user ID
    /// - `name`: user name
    /// - `email`: optional email address
    /// - `tags`: list of user tags
    pub fn process_user(
        &self,
        user_id: i32,
        name: String,
        _email: Option<String>,
        tags: Vec<String>,
    ) -> String {
        format!(
            "Processed user {} ({}): tag count = {}",
            user_id,
            name,
            tags.len()
        )
    }

    /// Compute numeric statistics
    ///
    /// - `numbers`: list of numbers to analyze
    /// - `include_median`: whether to include the median
    pub fn calculate_stats(
        &self,
        numbers: Vec<f64>,
        include_median: Option<bool>,
    ) -> HashMap<String, f64> {
        let mut stats = HashMap::new();

        if !numbers.is_empty() {
            let sum: f64 = numbers.iter().sum();
            let count = numbers.len() as f64;
            stats.insert("sum".to_string(), sum);
            stats.insert("count".to_string(), count);
            stats.insert("average".to_string(), sum / count);

            if include_median.unwrap_or(false) {
                let mut sorted = numbers.clone();
                sorted.sort_by(|a, b| a.partial_cmp(b).unwrap());
                let mid = sorted.len() / 2;
                let median = if sorted.len().is_multiple_of(2) {
                    (sorted[mid - 1] + sorted[mid]) / 2.0
                } else {
                    sorted[mid]
                };
                stats.insert("median".to_string(), median);
            }
        }

        stats
    }

    /// Process nested optional parameters
    ///
    /// - `id`: required ID
    /// - `name`: optional name
    /// - `count`: optional count
    /// - `note`: double optional
    pub fn process_optional(
        &self,
        id: i32,
        name: Option<String>,
        count: Option<i32>,
        note: Option<Option<String>>,
    ) -> String {
        format!(
            "ID: {}, Name: {:?}, Count: {:?}, Note: {:?}",
            id, name, count, note
        )
    }

    /// Process an array reference
    ///
    /// - `data`: data slice
    pub fn process_slice(&self, data: Vec<i32>) -> i32 {
        data.iter().sum()
    }

    /// Process tuple parameter (flattened to array)
    ///
    /// - `coordinates`: coordinate data
    pub fn process_tuple_data(&self, coordinates: (i32, i32)) -> String {
        format!("Coordinates: ({}, {})", coordinates.0, coordinates.1)
    }

    // ========== Parameter attribute feature demonstration ==========

    /// Create a user (with automatic validation)
    ///
    /// Demonstrates automatic validation and transformation via doc-comment syntax
    ///
    /// @param name user's name (must not be empty)
    /// @validate name !value.is_empty()
    /// @param email user's email
    /// @param age user's age (must be between 0 and 150)
    /// @validate age value > 0 && value < 150
    /// @required name
    /// @required age
    #[tool(alias = ["create_user_account", "add_user"])]
    pub fn create_user(
        &self,
        name: String,
        email: String,
        age: i32,
    ) -> Result<String, tokitai::ToolError> {
        // Validation is auto-generated by the macro
        Ok(format!(
            "Created user: {} (email: {}, age: {})",
            name, email, age
        ))
    }

    /// Get a user
    ///
    /// @param user_id user ID
    #[tool(alias = ["get_user_info", "fetch_user"])]
    pub fn get_user(&self, user_id: i32) -> Result<String, tokitai::ToolError> {
        Ok(format!("Fetched user: {}", user_id))
    }

    /// Parameter attribute test
    ///
    /// Demonstrates the three tool-description styles and parameter-level attributes
    ///
    /// @param name user's name
    /// @param age user's age
    /// @param email email address
    #[tool(
        desc = "Returns a greeting String built from the supplied user fields (name, age, email). Validates name length and age range; requires the email parameter to be a valid String address.",
        tags = ["demo", "test"],
        example_name = "Alice",
        min_length_name = 1,
        max_length_name = 50,
        min_age = 0,
        max_age = 150,
        example_email = "test@example.com"
    )]
    pub fn method_with_param_attrs(
        &self,
        name: String,
        _age: i32,
        email: Option<String>,
    ) -> String {
        format!("{} <{}>", name, email.unwrap_or_default())
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    println!("=== Advanced Type Support Example ===\n");

    let tools = AdvancedTools;

    // ========== Part 1: Advanced type support ==========
    println!("[Part 1] Advanced Type Support\n");

    // Show tool definitions
    println!("1. Tool definitions (inspect the generated JSON Schema)");
    for tool in AdvancedTools::tool_definitions() {
        println!("\n   Tool: {}", tool.name);
        println!("   Description: {}", tool.description);
        println!("   Schema: {}", tool.input_schema);
    }
    println!();

    // Test process_user
    println!("2. Test process_user");
    let result = tools.call_tool(
        "process_user",
        &tokitai::json!({
            "user_id": 123,
            "name": "Alice",
            "email": "alice@example.com",
            "tags": ["admin", "active"]
        }),
    )?;
    println!("   Result: {}", result);
    println!();

    // Test calculate_stats
    println!("3. Test calculate_stats");
    let result = tools.call_tool(
        "calculate_stats",
        &tokitai::json!({
            "numbers": [1.0, 2.0, 3.0, 4.0, 5.0],
            "include_median": true
        }),
    )?;
    println!("   Statistics: {}", result);
    println!();

    // Test optional parameters
    println!("4. Test optional parameters");
    let result = tools.call_tool(
        "process_optional",
        &tokitai::json!({
            "id": 42,
            "name": "Test",
            "count": null,
            "note": null
        }),
    )?;
    println!("   Result: {}", result);
    println!();

    // Test slice summing
    println!("5. Test process_slice");
    let result = tools.call_tool(
        "process_slice",
        &tokitai::json!({
            "data": [1, 2, 3, 4, 5]
        }),
    )?;
    println!("   Sum result: {}", result);
    println!();

    // ========== Part 2: Parameter attribute features ==========
    println!("\n[Part 2] Parameter Attributes (validation, transformation, aliases)\n");

    // Test create_user (with validation and transformation)
    println!("6. Test create_user (with validation)");

    // Test 1: normal call
    let args = tokitai::json!({
        "name": "Alice",
        "email": "ALICE@EXAMPLE.COM",
        "age": 25
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("   Success: {}", result),
        Err(e) => println!("   Error: {}", e),
    }

    // Test 2: use an alias
    let args = tokitai::json!({
        "name": "Bob",
        "email": "BOB@EXAMPLE.COM",
        "age": 30
    });
    match tools.call_tool("create_user_account", &args) {
        Ok(result) => println!("   Alias success: {}", result),
        Err(e) => println!("   Error: {}", e),
    }

    // Test 3: validation failure - empty name
    let args = tokitai::json!({
        "name": "",
        "email": "test@example.com",
        "age": 25
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("   Success: {}", result),
        Err(e) => println!("   Validation failure (expected): {}", e),
    }

    // Test 4: validation failure - age out of range
    let args = tokitai::json!({
        "name": "Carol",
        "email": "carol@example.com",
        "age": 200
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("   Success: {}", result),
        Err(e) => println!("   Validation failure (expected): {}", e),
    }

    // Test 5: test get_user aliases
    println!("\n7. Test get_user aliases");
    let args = tokitai::json!({"user_id": 123});
    match tools.call_tool("get_user", &args) {
        Ok(result) => println!("   get_user: {}", result),
        Err(e) => println!("   Error: {}", e),
    }

    let args = tokitai::json!({"user_id": 456});
    match tools.call_tool("get_user_info", &args) {
        Ok(result) => println!("   get_user_info: {}", result),
        Err(e) => println!("   Error: {}", e),
    }

    // Test 6: parameter attributes
    println!("\n8. Test method_with_param_attrs");
    let result = tools.call_tool(
        "method_with_param_attrs",
        &tokitai::json!({
            "name": "Dave",
            "age": 30,
            "email": "dave@example.com"
        }),
    )?;
    println!("   Result: {}", result);

    println!("\n=== All tests complete ===");

    Ok(())
}
