//! Example demonstrating the validate, transform, and alias features
//! Showcases the macro's automatic validation and transformation capabilities (no manual validation code required)

use tokitai::tool;
use tokitai::ToolProvider;

#[tool]
pub struct MyTools;

#[tool]
impl MyTools {
    /// Create a user (with automatic validation)
    ///
    /// Demonstrates automatic validation and transformation using doc comment syntax
    ///
    /// @param name The user's name (must not be empty)
    /// @validate name !value.is_empty()
    /// @param email The user's email
    /// @param age The user's age (must be between 0 and 150)
    /// @validate age value > 0 && value < 150
    /// @required name
    /// @required age
    #[tool(alias = ["create_user_account", "add_user"])]
    pub fn create_user(
        &self,
        name: String,
        email: String,
        age: i32,
    ) -> Result<String, tokitai::ToolError> {
        // Validation is automatically generated by the macro
        Ok(format!(
            "Created user: {} (email: {}, age: {})",
            name, email, age
        ))
    }

    /// Get a user
    ///
    /// @param user_id The user's ID
    #[tool(alias = ["get_user_info", "fetch_user"])]
    pub fn get_user(&self, user_id: i32) -> Result<String, tokitai::ToolError> {
        Ok(format!("Fetched user: {}", user_id))
    }
}

fn main() {
    let tools = MyTools;

    // Test aliases
    println!("=== Test tool definitions ===");
    for def in MyTools::tool_definitions() {
        println!("Tool: {}", def.name);
        println!("Description: {}", def.description);
        println!("Schema: {}", def.input_schema);
        println!();
    }

    // Test create_user (with validation and transformation)
    println!("=== Test create_user ===");

    // Test 1: Normal call
    let args = tokitai::json!({
        "name": "Alice",
        "email": "ALICE@EXAMPLE.COM",
        "age": 25
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("Success: {}", result),
        Err(e) => println!("Error: {}", e),
    }

    // Test 2: Use an alias
    let args = tokitai::json!({
        "name": "Bob",
        "email": "BOB@EXAMPLE.COM",
        "age": 30
    });
    match tools.call_tool("create_user_account", &args) {
        Ok(result) => println!("Alias success: {}", result),
        Err(e) => println!("Error: {}", e),
    }

    // Test 3: Use another alias
    let args = tokitai::json!({
        "name": "Charlie",
        "email": "CHARLIE@EXAMPLE.COM",
        "age": 35
    });
    match tools.call_tool("add_user", &args) {
        Ok(result) => println!("Another alias success: {}", result),
        Err(e) => println!("Error: {}", e),
    }

    // Test 4: Validation failure - empty name
    let args = tokitai::json!({
        "name": "",
        "email": "test@example.com",
        "age": 25
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("Success: {}", result),
        Err(e) => println!("Validation failed (expected): {}", e),
    }

    // Test 5: Validation failure - age out of range
    let args = tokitai::json!({
        "name": "Dave",
        "email": "dave@example.com",
        "age": 200
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("Success: {}", result),
        Err(e) => println!("Validation failed (expected): {}", e),
    }

    // Test 6: Test email transformation (should be lowercased)
    let args = tokitai::json!({
        "name": "TestUser",
        "email": "TEST@EXAMPLE.COM",
        "age": 28
    });
    match tools.call_tool("create_user", &args) {
        Ok(result) => println!("Email transformation result: {}", result),
        Err(e) => println!("Error: {}", e),
    }

    // Test 7: Test get_user aliases
    println!("\n=== Test get_user aliases ===");
    let args = tokitai::json!({"user_id": 123});
    match tools.call_tool("get_user", &args) {
        Ok(result) => println!("get_user: {}", result),
        Err(e) => println!("Error: {}", e),
    }

    let args = tokitai::json!({"user_id": 456});
    match tools.call_tool("get_user_info", &args) {
        Ok(result) => println!("get_user_info: {}", result),
        Err(e) => println!("Error: {}", e),
    }

    let args = tokitai::json!({"user_id": 789});
    match tools.call_tool("fetch_user", &args) {
        Ok(result) => println!("fetch_user: {}", result),
        Err(e) => println!("Error: {}", e),
    }
}
