//! T-024: runtime cross-crate version assertion for
//! `tokitai-mcp-server::serve()`.
//!
//! The server reads `--require-tokitai=<prefix>` and
//! `--allow-tokitai-mismatch` from `std::env::args`, then compares
//! the manifest version (emitted by `build.rs`) against the
//! requested prefix. On mismatch the function returns
//! `Err(ServerError::ServerStartupError(...))` so the surrounding
//! `main` can exit with code 78 (`EX_CONFIG`).
//!
//! ## Design
//!
//! - **No `clap` / no new deps.** T-024 deliberately keeps the
//!   parser in `std::env::args` so the hard-rule "no new top-level
//!   dependencies" stays intact. The two flags are parsed with a
//!   single linear scan over `args`.
//! - **Pure helper, no IO.** The match function
//!   ([`version_matches_prefix`]) is exposed as a `pub` pure
//!   helper so the unit tests can cover every branch without
//!   binding a port.
//! - **Audit trail.** When `--allow-tokitai-mismatch` is set, the
//!   override is logged at `warn!` level so the surrounding
//!   orchestration system can scrape the audit log for the
//!   override.
//!
//! ## CLI contract
//!
//! | Flag                              | Default                | Meaning |
//! |-----------------------------------|------------------------|---------|
//! | `--require-tokitai=<prefix>`      | manifest version       | Required SemVer prefix. The manifest's `TOKITAI_VERSION` must satisfy this rule. |
//! | `--allow-tokitai-mismatch`        | `false`                | Bypass the prefix check. Logged at `warn!` so the audit trail records the override. |
//!
//! The manifest version is sourced from
//! `OUT_DIR/tokitai_manifest.rs`, generated by `build.rs`. It
//! carries the resolved `tokitai-core` version the server was
//! compiled against (via the `DEP_TOKITAI_CORE_VERSION` env var
//! Cargo populates for direct deps).
//!
//! ## Hard refusal (default) vs soft warn (override)
//!
//! Per todo.json v3.0 Q-12: the default behaviour is a hard
//! refusal (caller propagates the error and exits 78). The
//! `--allow-tokitai-mismatch` flag is the documented escape hatch
//! for emergency deploys; it is logged at `warn!` so the audit
//! trail records the override.

use crate::ServerError;

/// The compile-time-resolved `tokitai-core` version the server
/// was built against. Emitted by `build.rs` via
/// `OUT_DIR/tokitai_manifest.rs`; `include!`-ed here so the
/// constant is baked into the binary at compile time and cannot
/// drift between the manifest write and the runtime read.
const TOKITAI_VERSION: &str = tokitai_manifest::TOKITAI_VERSION;

/// Inline the manifest module emitted by `build.rs`. The
/// generated file declares `pub const TOKITAI_VERSION` directly
/// at module scope. The `include!` brings the constant into this
/// `tokitai_manifest` module without a separate source file
/// leaking out of the crate.
#[allow(non_snake_case)]
mod tokitai_manifest {
    include!(concat!(env!("OUT_DIR"), "/tokitai_manifest.rs"));
}

/// Outcome of parsing the two CLI flags
/// (`--require-tokitai=<prefix>` and `--allow-tokitai-mismatch`).
/// Returned by [`parse_serve_args`] so the unit tests can cover
/// every branch without binding a port.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ServeArgs {
    /// The SemVer prefix the manifest must satisfy. When `None`
    /// the manifest version is accepted as-is (no-op check).
    pub require_tokitai: Option<String>,
    /// When `true`, the prefix check is bypassed. The bypass is
    /// logged at `warn!` level so the audit trail records the
    /// override.
    pub allow_mismatch: bool,
}

/// Parse the two CLI flags out of `std::env::args()`. The
/// function is `pub(crate)` so unit tests can exercise it
/// directly with a fake argv.
///
/// Flags recognised:
///
/// * `--require-tokitai=<prefix>` (the value is anything after
///   the first `=`; whitespace inside the prefix is not
///   supported, but typical SemVer strings contain no
///   whitespace).  An empty or whitespace-only prefix is
///   rejected as an operator error — it would silently
///   disable the version check.
/// * `--allow-tokitai-mismatch` (no value).
///
/// Unknown flags are ignored. The function never panics.
pub(crate) fn parse_serve_args<I, S>(args: I) -> Result<ServeArgs, &'static str>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut out = ServeArgs {
        require_tokitai: None,
        allow_mismatch: false,
    };
    for arg in args {
        let a = arg.as_ref();
        if let Some(rest) = a.strip_prefix("--require-tokitai=") {
            if rest.trim().is_empty() {
                return Err(
                    "operator error: --require-tokitai=<prefix> requires a non-empty \
                     prefix (use --allow-tokitai-mismatch to bypass the version check)",
                );
            }
            out.require_tokitai = Some(rest.to_string());
        } else if a == "--allow-tokitai-mismatch" {
            out.allow_mismatch = true;
        }
        // Unknown flags: ignore (forward compatibility).
    }
    Ok(out)
}

/// The manifest entry the `serve()` function returns to the
/// caller so unit tests can assert which constant was used.
/// Pure / no IO.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServeVersionCheck {
    /// The manifest's resolved `tokitai-core` version.
    pub manifest_version: &'static str,
    /// The SemVer prefix the caller asked for, if any.
    pub require_prefix: Option<String>,
    /// `true` when the manifest version satisfies the prefix.
    pub matches: bool,
}

/// Decide whether `manifest` satisfies `prefix` under the T-024
/// prefix rule (1 component matches any on the same major;
/// 2 components match any on the same major.minor; 3 components
/// must match exactly). The `v` prefix is accepted
/// transparently.
///
/// Returns `true` when `prefix` is `None` (no requirement
/// specified — the function is a no-op).
///
/// Returns `false` when either side is empty / not a valid
/// SemVer string. The function does not panic.
pub fn version_matches_prefix(manifest: &str, prefix: Option<&str>) -> bool {
    let Some(p) = prefix else {
        return true;
    };
    let p = p.trim();
    if p.is_empty() {
        return true;
    }
    let (manifest_maj, manifest_min, manifest_pat, _) = match parse_semver_tuple(manifest) {
        Some(v) => v,
        None => return false,
    };
    let (want_maj, want_min, want_pat, arity) = match parse_semver_tuple(p) {
        Some(v) => v,
        None => return false,
    };
    if arity >= 1 && manifest_maj != want_maj {
        return false;
    }
    if arity >= 2 && manifest_min != want_min {
        return false;
    }
    if arity >= 3 && manifest_pat != want_pat {
        return false;
    }
    true
}

/// T-024: pure prefix-match helper exposed for unit tests. The
/// non-const evaluator used here is identical in spirit to the
/// inline const-stable parser in `tokitai-core::assert_compatible_with`
/// but does not need to be `const fn` because the runtime path
/// runs at startup, not compile time.
pub(crate) fn parse_semver_tuple(s: &str) -> Option<(u64, u64, u64, usize)> {
    let s = s.trim();
    let s = s.strip_prefix('v').unwrap_or(s);
    let s = s.strip_prefix('V').unwrap_or(s);
    let core = s.split(['-', '+']).next().unwrap_or(s);
    let mut parts = core.split('.');
    let mut arity: usize = 0;
    let mut out: [u64; 3] = [0, 0, 0];
    // C-1: refuse a 4th component before iterating. This mirrors
    // the const guard added to `parse_semver_const` in
    // `tokitai-core`. The inner `arity >= 3` check below is
    // sufficient on its own today, but checking up-front keeps
    // this function safe even if a future refactor reorders the
    // inner loop body.
    let pre_count = core.split('.').count();
    if pre_count > 3 {
        return None;
    }
    for piece in &mut parts {
        if piece.is_empty() {
            return None;
        }
        // Reject leading-zero components (`01`) for canonical
        // SemVer compatibility.
        if piece.len() > 1 && piece.starts_with('0') {
            return None;
        }
        let v: u64 = piece.parse().ok()?;
        if arity >= 3 {
            return None;
        }
        out[arity] = v;
        arity += 1;
    }
    // Reject a trailing empty component (e.g. `"0.8."`).
    if let Some(last) = core.split('.').next_back() {
        if last.is_empty() {
            return None;
        }
    }
    if arity == 0 {
        return None;
    }
    Some((out[0], out[1], out[2], arity))
}

/// Run the T-024 startup check. Returns `Ok(())` when the
/// manifest version satisfies the requested prefix (or no prefix
/// was requested). Returns `Err(ServerError::ServerStartupError)`
/// on mismatch; the caller is expected to log the message and
/// exit 78.
///
/// The function is side-effecting on the `tracing` crate: a
/// successful check emits `info!`, a failed check emits `warn!`
/// and (when the override is set) another `warn!` recording the
/// audit-trail override.
///
/// This function does NOT bind any port. The caller
/// (`tokitai_mcp_server::serve`) is expected to:
/// 1. Call `check_version_at_startup` first.
/// 2. On `Err`, return the error to the caller (which then
///    exits 78).
/// 3. On `Ok`, proceed to build the server, bind, and serve.
pub(crate) fn check_version_at_startup(args: &ServeArgs) -> Result<(), ServerError> {
    let manifest = TOKITAI_VERSION;
    let matches = version_matches_prefix(manifest, args.require_tokitai.as_deref());

    if matches {
        tracing::info!(
            target: "tokitai_mcp_server::serve",
            "T-024 version check passed: manifest=`{}` require=`{:?}`",
            manifest,
            args.require_tokitai,
        );
        return Ok(());
    }

    // Mismatch path. Either refuse (default) or warn-and-allow
    // (when the operator set --allow-tokitai-mismatch).
    if args.allow_mismatch {
        tracing::warn!(
            target: "tokitai_mcp_server::serve",
            "T-024 version mismatch: manifest=`{}` require=`{:?}` -- --allow-tokitai-mismatch is set, continuing",
            manifest,
            args.require_tokitai,
        );
        return Ok(());
    }

    let msg = format!(
        "tokitai-core version mismatch: manifest=`{}` does not satisfy `--require-tokitai={}` \
         (refusing to start). Re-run with `--allow-tokitai-mismatch` for the documented \
         emergency override, or align your pinned `tokitai-core` with the requirement. \
         See https://docs.rs/tokitai-core for the migration guide.",
        manifest,
        args.require_tokitai.as_deref().unwrap_or(""),
    );
    tracing::warn!(
        target: "tokitai_mcp_server::serve",
        "T-024 version mismatch refused: {}",
        msg,
    );
    Err(ServerError::ServerStartupError(msg))
}

/// Top-level entry point. Reads `std::env::args`, runs the
/// version check, and (on success) prints a message instructing
/// the caller how to wire `McpServerBuilder::with_tool(...)`.
///
/// `serve()` is the documented CLI entry point. It deliberately
/// does NOT spin up an HTTP / stdio server itself — the caller
/// is expected to use `McpServerBuilder::with_tool(provider)` for
/// that. `serve()` exists as a one-shot guard that:
/// 1. Parses the two flags.
/// 2. Runs the T-024 check.
/// 3. Returns `Ok(())` so the caller knows it is safe to bind.
///
/// This split keeps the unit test surface tiny: the version
/// check can be exercised with a fake argv, without any port.
pub fn serve() -> Result<(), ServerError> {
    let args = parse_serve_args(std::env::args().skip(1))
        .map_err(|e| ServerError::ServerStartupError(e.to_string()))?;
    check_version_at_startup(&args)?;
    tracing::info!(
        target: "tokitai_mcp_server::serve",
        "T-024 cross-crate version check passed; caller may proceed to bind."
    );
    Ok(())
}

/// T-024: public re-export of the manifest's resolved
/// `tokitai-core` version. Useful for binary entry points that
/// want to log the resolved version alongside the check result
/// without re-parsing the lockfile. Integration tests use this
/// constant to assert the manifest is reachable.
pub fn manifest_version() -> &'static str {
    TOKITAI_VERSION
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_args_empty() {
        let args = parse_serve_args(Vec::<&str>::new()).unwrap();
        assert_eq!(
            args,
            ServeArgs {
                require_tokitai: None,
                allow_mismatch: false,
            }
        );
    }

    #[test]
    fn parse_args_require_only() {
        let args = parse_serve_args(vec!["--require-tokitai=0.8"]).unwrap();
        assert_eq!(args.require_tokitai.as_deref(), Some("0.8"));
        assert!(!args.allow_mismatch);
    }

    #[test]
    fn parse_args_allow_only() {
        let args = parse_serve_args(vec!["--allow-tokitai-mismatch"]).unwrap();
        assert_eq!(args.require_tokitai, None);
        assert!(args.allow_mismatch);
    }

    #[test]
    fn parse_args_both() {
        let args =
            parse_serve_args(vec!["--require-tokitai=0.9.0", "--allow-tokitai-mismatch"]).unwrap();
        assert_eq!(args.require_tokitai.as_deref(), Some("0.9.0"));
        assert!(args.allow_mismatch);
    }

    #[test]
    fn parse_args_unknown_flag_ignored() {
        let args = parse_serve_args(vec!["--unknown", "--require-tokitai=0.5"]).unwrap();
        assert_eq!(args.require_tokitai.as_deref(), Some("0.5"));
        assert!(!args.allow_mismatch);
    }

    #[test]
    fn parse_args_rejects_empty_require_prefix() {
        let result = parse_serve_args(vec!["--require-tokitai="]);
        assert!(result.is_err(), "empty prefix must be rejected");
        let err = result.unwrap_err();
        assert!(
            err.contains("non-empty"),
            "error message must mention the operator fix: got {:?}",
            err,
        );
    }

    #[test]
    fn parse_args_rejects_whitespace_prefix() {
        let result = parse_serve_args(vec!["--require-tokitai=   "]);
        assert!(result.is_err(), "whitespace-only prefix must be rejected");
    }

    #[test]
    fn parse_args_accepts_valid_prefix_with_leading_whitespace() {
        // The value after `=` is not trimmed, but the empty-check
        // rejects whitespace-only. A prefix with surrounding
        // whitespace is preserved as-is (callers handle it).
        let args = parse_serve_args(vec!["--require-tokitai=0.5"]).unwrap();
        assert_eq!(args.require_tokitai.as_deref(), Some("0.5"));
    }

    #[test]
    fn prefix_match_major_only() {
        // 1-component prefix: matches any version on the same major.
        assert!(version_matches_prefix("0.5.1", Some("0")));
        assert!(version_matches_prefix("0.5.1", Some("0")));
        assert!(!version_matches_prefix("0.5.1", Some("1")));
        assert!(version_matches_prefix("1.0.0", Some("1")));
        assert!(!version_matches_prefix("0.5.1", Some("2")));
    }

    #[test]
    fn prefix_match_major_minor() {
        assert!(version_matches_prefix("0.5.1", Some("0.5")));
        assert!(version_matches_prefix("0.5.99", Some("0.5")));
        assert!(!version_matches_prefix("0.6.0", Some("0.5")));
    }

    #[test]
    fn prefix_match_exact() {
        assert!(version_matches_prefix("0.5.1", Some("0.5.1")));
        assert!(!version_matches_prefix("0.5.1", Some("0.5.2")));
    }

    #[test]
    fn prefix_match_v_prefix_accepted() {
        assert!(version_matches_prefix("0.5.1", Some("v0.5")));
        assert!(version_matches_prefix("0.5.1", Some("V0.5.1")));
    }

    #[test]
    fn prefix_match_none_means_no_op() {
        assert!(version_matches_prefix("0.5.1", None));
        assert!(version_matches_prefix("anything", None));
    }

    #[test]
    fn prefix_match_empty_prefix_means_no_op() {
        assert!(version_matches_prefix("0.5.1", Some("")));
        assert!(version_matches_prefix("0.5.1", Some("  ")));
    }

    #[test]
    fn prefix_match_rejects_malformed_inputs() {
        // Both sides invalid -> false. The function never panics.
        assert!(!version_matches_prefix("garbage", Some("0.5")));
        assert!(!version_matches_prefix("0.5.1", Some("garbage")));
        assert!(!version_matches_prefix("", Some("0.5")));
    }

    #[test]
    fn prefix_match_rejects_leading_zero() {
        // Canonical SemVer disallows `01`. The parser returns
        // None for leading-zero components, so the helper
        // returns false.
        assert!(!version_matches_prefix("01.0.0", Some("0")));
    }

    #[test]
    fn check_version_at_startup_passes_for_matching_prefix() {
        let args = ServeArgs {
            require_tokitai: Some("0".to_string()),
            allow_mismatch: false,
        };
        // The manifest is whatever tokitai-core version this
        // build was compiled against. The major is always
        // pinned to `0` in this workspace.
        let result = check_version_at_startup(&args);
        assert!(
            result.is_ok(),
            "expected the manifest's major-0 prefix to match, got {:?}",
            result,
        );
    }

    #[test]
    fn check_version_at_startup_passes_for_no_prefix() {
        let args = ServeArgs {
            require_tokitai: None,
            allow_mismatch: false,
        };
        assert!(check_version_at_startup(&args).is_ok());
    }

    #[test]
    fn check_version_at_startup_refuses_mismatch() {
        let args = ServeArgs {
            require_tokitai: Some("999.0.0".to_string()),
            allow_mismatch: false,
        };
        let result = check_version_at_startup(&args);
        assert!(result.is_err(), "expected mismatch to be refused");
    }

    #[test]
    fn check_version_at_startup_allows_mismatch_with_override() {
        let args = ServeArgs {
            require_tokitai: Some("999.0.0".to_string()),
            allow_mismatch: true,
        };
        let result = check_version_at_startup(&args);
        assert!(
            result.is_ok(),
            "expected --allow-tokitai-mismatch to bypass the refusal"
        );
    }

    #[test]
    fn parse_semver_tuple_basic() {
        assert_eq!(parse_semver_tuple("0.5.1"), Some((0, 5, 1, 3)));
        assert_eq!(parse_semver_tuple("0.5"), Some((0, 5, 0, 2)));
        assert_eq!(parse_semver_tuple("1"), Some((1, 0, 0, 1)));
    }

    #[test]
    fn parse_semver_tuple_v_prefix() {
        assert_eq!(parse_semver_tuple("v0.5.1"), Some((0, 5, 1, 3)));
        assert_eq!(parse_semver_tuple("V1.2.3"), Some((1, 2, 3, 3)));
    }

    #[test]
    fn parse_semver_tuple_pre_release_ignored() {
        assert_eq!(parse_semver_tuple("0.5.1-rc.1"), Some((0, 5, 1, 3)));
        assert_eq!(parse_semver_tuple("0.5.1+build.42"), Some((0, 5, 1, 3)));
    }

    #[test]
    fn parse_semver_tuple_rejects_garbage() {
        assert_eq!(parse_semver_tuple(""), None);
        assert_eq!(parse_semver_tuple("garbage"), None);
        assert_eq!(parse_semver_tuple("0.5.x"), None);
        assert_eq!(parse_semver_tuple("0.5."), None);
        assert_eq!(parse_semver_tuple("01.0.0"), None);
        assert_eq!(parse_semver_tuple("0"), Some((0, 0, 0, 1)));
    }

    #[test]
    fn parse_semver_tuple_rejects_extra_component() {
        // C-1: a fourth component used to slip past the
        // `arity >= 3` guard in the inline parse path and
        // panic. The const parser in `tokitai-core` panicked
        // in const context; this runtime parser silently
        // returned Some((0, 0, 0, 3)) on `0.0.0.0` while
        // letting the fourth component go unobserved. Both
        // parsers must reject anything with more than three
        // components.
        assert_eq!(parse_semver_tuple("0.0.0.0"), None);
        assert_eq!(parse_semver_tuple("1.2.3.4"), None);
        assert_eq!(parse_semver_tuple("0.5.1.2.3"), None);
    }
}
