//! Code generation for the `#[wrap]` macro.
//!
//! The output is a mix of:
//! - A `new(client: T) -> Self` constructor.
//! - The same per-tool artifacts `#[tool]` produces (definitions,
//!   wrappers, dispatcher, `__TOOL_COUNT`, `__get_tool_definitions`).
//! - The two trait impls (`ToolProvider`, `ToolCaller`).
//!
//! All per-tool artifacts are produced by reusing the existing
//! `crate::tool::codegen::*` helpers; `#[wrap]` only adds the
//! constructor and the two trait impls.

use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::Type;

use super::WrapArgs;
use crate::tool::codegen::{definitions, dispatcher, wrappers};
use crate::tool::types::tool_method::ToolMethodInfo;

/// Build every per-impl item the macro will splice into the `impl` block.
pub(crate) fn generate(
    impl_ty: &Type,
    args: &WrapArgs,
    tool_methods: &[ToolMethodInfo],
) -> Vec<TokenStream2> {
    let mut out: Vec<TokenStream2> = Vec::new();

    // 1. `pub fn new(client: TYPE) -> Self { Self { client } }`.
    let client_ty = &args.client_ty;
    let client_field = &args.client_field;
    out.push(quote! {
        /// Construct a new wrapper around the given inner client.
        ///
        /// Generated by `#[wrap]`. Equivalent to a hand-written
        /// `Self { #client_field }` constructor; provided so the
        /// user does not have to write it for every wrapped type.
        #[allow(dead_code)]
        pub fn new(#client_field: #client_ty) -> Self {
            Self { #client_field: #client_field }
        }
    });

    // 2. `__TOOL_DEF_*` per-tool definition functions.
    for tokens in definitions::generate_tool_def_consts(tool_methods) {
        out.push(tokens);
    }

    // 3. `__TOOL_COUNT` constant (compile-time tool count).
    out.push(definitions::generate_tool_count_const(tool_methods));

    // 4. `__get_tool_definitions` (LazyLock-initialised, supports
    //    `tokitai!` config overrides at runtime).
    let all_tool_defs = definitions::generate_all_tool_defs_array(tool_methods, impl_ty);
    out.push(quote! {
        /// All tool definitions (runtime initialisation, supports config
        /// overrides). Mirrors the `#[tool]` implementation exactly.
        #[allow(dead_code)]
        fn __get_tool_definitions() -> &'static [::tokitai_core::ToolDefinition] {
            static TOOLS: ::std::sync::LazyLock<::std::vec::Vec<::tokitai_core::ToolDefinition>> =
                ::std::sync::LazyLock::new(|| {
                    let mut defs = ::std::vec::Vec::from([#(#all_tool_defs.clone()),*]);

                    for def in &mut defs {
                        let configs = ::tokitai_core::GLOBAL_CONFIG_REGISTRY.get(&def.name);
                        if !configs.is_empty() {
                            def.apply_configs(&configs);
                        }
                    }

                    defs
                });

            &TOOLS
        }
    });

    // 5. `call_tool` / `call_tool_sync` dispatcher.
    for tokens in dispatcher::generate_call_tool_method(tool_methods) {
        out.push(tokens);
    }

    // 6. `__call_*` wrapper methods (param parsing, validation, result
    //    serialisation, runtime-agnostic async bridge).
    for tokens in wrappers::generate_helper_methods(tool_methods) {
        out.push(tokens);
    }

    // 7. `configure_tool` runtime override hook (same as `#[tool]`).
    out.push(quote! {
        /// Override a tool's metadata at runtime via the `tokitai!`
        /// config registry. Mirrors the `#[tool]` implementation.
        #[allow(dead_code)]
        pub fn configure_tool(_tool_name: &str, _configs: &[::tokitai_core::ToolConfig]) {
            ::tokitai_core::GLOBAL_CONFIG_REGISTRY.configure(_tool_name, _configs);
            let _ = Self::__get_tool_definitions();
        }
    });

    out
}

/// `impl ::tokitai_core::ToolProvider for #impl_ty { ... }`
pub(crate) fn tool_provider_impl(impl_ty: &Type) -> TokenStream2 {
    quote! {
        impl ::tokitai_core::ToolProvider for #impl_ty {
            fn tool_definitions() -> &'static [::tokitai_core::ToolDefinition] {
                Self::__get_tool_definitions()
            }

            fn tool_count() -> usize {
                Self::__TOOL_COUNT
            }
        }
    }
}

/// `impl ::tokitai_core::ToolCaller for #impl_ty { ... }`.
///
/// Forwards to the in-impl `call_tool` method generated by the
/// dispatcher step above. Mirrors the `#[tool]` macro's forwarding
/// strategy so the same call-site ergonomics apply.
pub(crate) fn tool_caller_impl(impl_ty: &Type) -> TokenStream2 {
    quote! {
        impl ::tokitai_core::ToolCaller for #impl_ty {
            fn call_tool(
                &self,
                name: &str,
                args: &::tokitai_core::serde_types::Value,
            ) -> Result<::tokitai_core::serde_types::Value, ::tokitai_core::ToolError> {
                self.call_tool(name, args)
            }
        }
    }
}
