//! T-017: `#[compose(name = "...", steps = [a, b, c])]` declarative
//! multi-step tool composition.
//!
//! The `#[compose]` attribute lives on an `impl` block. It collapses
//! a sequence of named `pub` methods into a SINGLE tool the LLM
//! calls once. The macro generates:
//!
//! 1. A `__call_<name>` wrapper that calls the named sub-methods in
//!    order, threading the output of step N into the first non-`self`
//!    argument of step N+1.
//! 2. A `__TOOL_DEF_<NAME>` const whose `input_schema` is the first
//!    step's input schema. The composed tool appears as one entry
//!    in the `__get_tool_definitions()` slice and one arm in the
//!    `call_tool` dispatcher.
//! 3. A synthetic public method on the impl block (the same impl
//!    that the user wrote) whose signature matches the composed
//!    tool's contract. The `#[tool]` codegen (which runs in the
//!    same expansion pass) sees the synthetic method and registers
//!    it as a regular tool entry. The synthetic method is never
//!    invoked directly: the dispatcher routes the composed call to
//!    `__call_<name>`, which in turn calls the user's real
//!    sub-methods in order.
//!
//! ## Compile-time checks
//!
//! - Every named step method exists on the same `impl` block (E0001
//!   with a "did you mean" suggestion when there's a near-miss).
//! - The chain of types connects: step N's return type is exactly
//!   the same as step N+1's first non-`self` argument type. Same-
//!   type check is what v1 ships (Q-8: v1 is sequential only).
//! - The composition is acyclic: no name appears twice in `steps`.
//!
//! All diagnostics are anchored at the `steps = [...]` span (or the
//! offending ident inside the brackets) per T-001.
//!
//! ## v1 scope
//!
//! Sequential only. The composed tool is a `pub fn` on the impl
//! block with the first step's first non-`self` parameters and the
//! last step's return type. The body is generated by the macro and
//! calls the named sub-methods in order. The `#[tool]` codegen
//! picks up the synthetic method through the regular
//! `collect_tool_methods` pass.
//!
//! ## Backwards compatibility
//!
//! `#[compose]` is a NEW attribute. Existing `#[tool]` impls without
//! it are unaffected. The attribute is orthogonal: the same impl
//! block can carry `#[tool]` AND `#[compose]`; both attributes are
//! read in the same expansion pass.
//!
//! ## See also
//!
//! - `docs/AI_INTEGRATION.md` §"Composing tools" — the user-facing
//!   rationale and the token-savings table.
//! - `tokitai/tests/compose_test.rs` — the test surface.

use proc_macro::TokenStream;
use proc_macro2::Span;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote, ToTokens};
use syn::parse::{Parse, ParseStream};
use syn::{Attribute, FnArg, Ident, ImplItem, ImplItemFn, ItemImpl, Pat, PatType, Type};

use crate::error::{format_did_you_mean, MacroError};

/// Attributes accepted by `#[compose(...)]`.
///
/// `name` is the composed tool's name (the LLM sees this as one
/// tool entry). `steps` is the ordered list of method idents
/// (without `self`) that will be called in sequence. The macro
/// generates one synthetic method (named `__compose_<name>`) and
/// one wrapper (`__call_<name>`) that threads the chain.
pub struct ComposeAttrs {
    pub name: String,
    pub steps: Vec<Ident>,
    /// Span of the `steps = [...]` array for error anchoring.
    pub steps_span: Span,
}

impl Parse for ComposeAttrs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        // Empty input is invalid: the user must supply at least `name`
        // and `steps`. We surface a clear error anchored at the empty
        // span so the user sees the failure at the attribute body.
        if input.is_empty() {
            return Err(input.error(
                "#[compose] requires `name = \"...\"` and `steps = [method, method, ...]`",
            ));
        }

        let mut name: Option<(String, Span)> = None;
        let mut steps: Option<(Vec<Ident>, Span)> = None;
        let attr_span = input.span();

        while !input.is_empty() {
            let key: Ident = input.parse()?;
            input.parse::<syn::token::Eq>()?;

            match key.to_string().as_str() {
                "name" => {
                    let lit: syn::LitStr = input.parse()?;
                    name = Some((lit.value(), lit.span()));
                }
                "steps" => {
                    let content;
                    syn::bracketed!(content in input);
                    let steps_span = content.span();
                    let mut step_idents = Vec::new();
                    while !content.is_empty() {
                        let ident: Ident = content.parse()?;
                        step_idents.push(ident);
                        if content.peek(syn::token::Comma) {
                            content.parse::<syn::token::Comma>()?;
                        }
                    }
                    if step_idents.is_empty() {
                        return Err(syn::Error::new(
                            steps_span,
                            "#[compose] `steps = [...]` must name at least one method",
                        ));
                    }
                    steps = Some((step_idents, steps_span));
                }
                other => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!(
                            "unknown `#[compose]` argument `{}`; expected `name` or `steps`",
                            other
                        ),
                    ));
                }
            }

            if input.peek(syn::token::Comma) {
                input.parse::<syn::token::Comma>()?;
            }
        }

        let (name_str, name_span) = name.ok_or_else(|| {
            syn::Error::new(
                attr_span,
                "#[compose] is missing the required `name = \"...\"` argument",
            )
        })?;
        let (step_idents, steps_span) = steps.ok_or_else(|| {
            syn::Error::new(
                attr_span,
                "#[compose] is missing the required `steps = [method, ...]` argument",
            )
        })?;

        if name_str.is_empty() {
            return Err(syn::Error::new(
                name_span,
                "#[compose] `name = \"...\"` must not be empty",
            ));
        }

        Ok(ComposeAttrs {
            name: name_str,
            steps: step_idents,
            steps_span,
        })
    }
}

/// Information about one named step in a `#[compose]` chain. Used
/// during the validation pass; not exposed outside this module.
struct StepInfo {
    ident: Ident,
    /// First non-`self` parameter type. Used as the input to
    /// this step (or the input to the composed tool, for step 0).
    first_input_ty: Type,
    /// All non-`self` parameter *names* in order (the first one
    /// is the "threaded" slot; the rest are pass-through).
    param_names: Vec<Ident>,
    /// All non-`self` parameter *types* in order.
    param_types: Vec<Type>,
    /// The step's return type (or `()` for the unit return).
    return_type: Type,
}

/// Resolve one named step to its signature info, or emit a
/// `compile_error!` at the step ident's span with a "did you
/// mean" suggestion.
fn resolve_step(step_ident: &Ident, impl_item: &ItemImpl) -> Result<StepInfo, MacroError> {
    // Collect the names of every public `pub fn` on the impl
    // block. We restrict to `pub` because the same rule already
    // applies to the standalone `#[tool]` attribute (T-001):
    // non-`pub` methods cannot be called from outside the impl,
    // and the LLM-facing dispatcher cannot call them either.
    let available: Vec<String> = impl_item
        .items
        .iter()
        .filter_map(|item| {
            if let ImplItem::Fn(fn_item) = item {
                if matches!(fn_item.vis, syn::Visibility::Public(_)) {
                    let name = fn_item.sig.ident.to_string();
                    if !name.starts_with("__") {
                        return Some(name);
                    }
                }
            }
            None
        })
        .collect();

    // Find the matching method. We do an O(n) scan because the
    // typical chain length is 2-5; the available set is the
    // impl's full method list which is also small.
    for item in &impl_item.items {
        if let ImplItem::Fn(fn_item) = item {
            if fn_item.sig.ident == *step_ident {
                if !matches!(fn_item.vis, syn::Visibility::Public(_)) {
                    return Err(MacroError::new(
                        crate::error::ErrorCode::E0001,
                        step_ident.span(),
                        format!(
                            "method `{}` listed in `steps = [...]` is not `pub`",
                            step_ident
                        ),
                    )
                    .with_help(
                        "make the step method `pub fn` so the dispatcher can call it; \
                         compose only accepts public methods on the same `impl` block",
                    ));
                }
                if !fn_item.sig.generics.params.is_empty() {
                    return Err(MacroError::new(
                        crate::error::ErrorCode::E0004,
                        step_ident.span(),
                        format!(
                            "method `{}` listed in `steps = [...]` is generic; \
                             `#[compose]` v1 does not support generic steps",
                            step_ident
                        ),
                    )
                    .with_help(
                        "use a concrete type in the step's signature, or take a \
                         `serde_json::Value` and deserialize inside the body",
                    ));
                }

                // Walk the inputs, separating `self` from the rest.
                let mut param_names: Vec<Ident> = Vec::new();
                let mut param_types: Vec<Type> = Vec::new();
                let mut has_self = false;
                for input in &fn_item.sig.inputs {
                    if let FnArg::Receiver(_) = input {
                        has_self = true;
                        continue;
                    }
                    if let FnArg::Typed(PatType { pat, ty, .. }) = input {
                        if let Pat::Ident(ident) = pat.as_ref() {
                            param_names.push(ident.ident.clone());
                            param_types.push(ty.as_ref().clone());
                        }
                    }
                }
                if !has_self {
                    return Err(MacroError::new(
                        crate::error::ErrorCode::E0012,
                        step_ident.span(),
                        format!(
                            "method `{}` listed in `steps = [...]` has no `self` parameter",
                            step_ident
                        ),
                    )
                    .with_help(
                        "compose steps must be instance methods with a `&self` receiver; \
                         the macro generates a `self.<step>(args)` call site",
                    ));
                }
                if param_names.is_empty() {
                    return Err(MacroError::new(
                        crate::error::ErrorCode::E0021,
                        step_ident.span(),
                        format!(
                            "method `{}` listed in `steps = [...]` takes no arguments; \
                             the first step must declare the composed tool's inputs",
                            step_ident
                        ),
                    )
                    .with_help(
                        "give the first step a parameter (e.g. `&self, query: String`); \
                         every step after the first consumes the previous step's return value",
                    ));
                }

                let first_input_ty = param_types[0].clone();
                let return_type = match &fn_item.sig.output {
                    syn::ReturnType::Default => syn::Type::Tuple(syn::TypeTuple {
                        paren_token: syn::token::Paren::default(),
                        elems: syn::punctuated::Punctuated::new(),
                    }),
                    syn::ReturnType::Type(_, ty) => ty.as_ref().clone(),
                };

                return Ok(StepInfo {
                    ident: step_ident.clone(),
                    first_input_ty,
                    param_names,
                    param_types,
                    return_type,
                });
            }
        }
    }

    // The named step does not exist. Build a "did you mean"
    // diagnostic and surface it at the step ident's span.
    let mut err = MacroError::new(
        crate::error::ErrorCode::E0001,
        step_ident.span(),
        format!(
            "method `{}` listed in `steps = [...]` does not exist on this `impl` block",
            step_ident
        ),
    )
    .with_help(
        "the `steps = [...]` list must name public methods defined in this `impl` block; \
         check spelling and that the method is `pub`",
    );
    let target = step_ident.to_string();
    let mut candidates: Vec<String> = available.clone();
    candidates.push(target.clone());
    let suggestions = crate::error::suggest_closest(&target, &candidates)
        .into_iter()
        .filter(|s| *s != target)
        .collect::<Vec<_>>();
    if let Some(text) = format_did_you_mean(&suggestions) {
        err = err.with_suggestion(text);
    }
    Err(err)
}

/// Run every validation we know how to run on a `#[compose]`
/// chain. The caller emits the returned diagnostics as
/// `compile_error!` invocations anchored at the per-step span.
fn validate_chain(steps: &[StepInfo], attrs: &ComposeAttrs) -> Vec<MacroError> {
    let mut errs = Vec::new();

    // Acyclicity: no step name appears twice. The check is
    // O(n^2) on the steps list, but a chain is at most a few
    // entries long, so the quadratic cost is irrelevant.
    for (i, a) in steps.iter().enumerate() {
        for b in steps.iter().skip(i + 1) {
            if a.ident == b.ident {
                errs.push(
                    MacroError::new(
                        crate::error::ErrorCode::E0001,
                        b.ident.span(),
                        format!(
                            "method `{}` appears twice in `steps = [...]`; \
                             a composed chain must be acyclic",
                            b.ident
                        ),
                    )
                    .with_help(
                        "remove the duplicate entry from `steps = [...]`; \
                         compose does not support cycles (a step cannot call itself, \
                         directly or transitively)",
                    ),
                );
            }
        }
    }

    // Type chain: the first step takes the composed tool's
    // inputs; step N+1's first non-`self` argument type must
    // match step N's return type.
    //
    // v1 ships a same-type check. Trait-bound reasoning
    // (`T: Into<U>`, etc.) is a v2 enhancement.
    for window in steps.windows(2) {
        let prev = &window[0];
        let next = &window[1];
        if !types_match(&prev.return_type, &next.first_input_ty) {
            let prev_ty = type_to_string(&prev.return_type);
            let next_ty = type_to_string(&next.first_input_ty);
            errs.push(
                MacroError::new(
                    crate::error::ErrorCode::E0001,
                    next.ident.span(),
                    format!(
                        "compose chain type mismatch: step `{}` returns `{}`, \
                         but step `{}` expects `{}` as its first argument",
                        prev.ident, prev_ty, next.ident, next_ty
                    ),
                )
                .with_help(format!(
                    "make step `{}`'s first argument type `{}` (matching the previous step's \
                     return type), or change step `{}`'s return type to match what `{}` expects",
                    next.ident, prev_ty, prev.ident, next.ident
                )),
            );
        }
    }

    // Anchor every compose error at the `steps = [...]` span
    // (or the offending ident) so the user sees the diagnostic
    // in the right place. The `validate_chain` helper above
    // already anchors each individual error; the caller still
    // emits them through `to_compile_error!` so the spans
    // survive into the user's editor.

    // Defensive: confirm the user actually provided more than
    // one step. A single-step compose is just a rename; the
    // `#[tool]` attribute's `name = "..."` already covers that.
    if steps.len() < 2 {
        errs.push(
            MacroError::new(
                crate::error::ErrorCode::E0001,
                attrs.steps_span,
                "#[compose] `steps = [...]` must name at least two methods; \
                 a single-step compose is equivalent to `#[tool(name = \"...\")]`",
            )
            .with_help(
                "add at least one more method to the `steps = [...]` list, or remove the \
                 `#[compose]` attribute and use `#[tool(name = \"...\")]` on the single method",
            ),
        );
    }

    // Silenced: the unique span warning. The cyclomatic step
    // detection is already strict enough that the helper above
    // catches every duplicate; this comment exists so a future
    // reader doesn't think the Set is missing.

    errs
}

/// Heuristic same-type check. We compare the rendered tokens
/// (the same string the user wrote) and treat structurally
/// identical token streams as the same type. This is the same
/// "good enough" check the existing schema generator uses for
/// path types.
fn types_match(a: &Type, b: &Type) -> bool {
    a.to_token_stream().to_string() == b.to_token_stream().to_string()
}

/// Render a `syn::Type` to a deterministic string for diagnostic
/// messages. We use `quote::ToTokens` so the output matches the
/// user's source shape (`String`, `Vec<i32>`, `MyStruct`, etc.).
fn type_to_string(ty: &Type) -> String {
    ty.to_token_stream().to_string()
}

/// Build the synthetic public method the `#[tool]` codegen will
/// pick up and register as the composed tool. The synthetic
/// method's name is `<name>` (the composed tool's name). The
/// codegen's regular `__call_<name>` machinery wraps it for
/// the LLM.
///
/// In practice: the synthetic method is `pub fn <name>(&self,
/// <union-of-step-args>) -> <last-step-return>` and its body
/// is the generated chain. The `#[tool]` codegen's regular
/// `__call_<name>` wrapper parses the args, calls
/// `self.<name>(args)`, and the synthetic body threads them
/// through the named sub-methods.
///
/// The synthetic method's parameter list is the union of the
/// first step's parameters and any extra parameters added by
/// later steps. The first step's parameters are in the order
/// the user wrote them; any additional parameters from later
/// steps are appended in the order they first appear. This
/// way the call site `self.<step>(<prev>, <pass-through>)`
/// can refer to a parameter that exists in the synthetic
/// method's scope.
fn build_synthetic_method(
    name: &str,
    first_step: &StepInfo,
    last_step: &StepInfo,
    steps: &[StepInfo],
) -> ImplItemFn {
    // Build the union of parameter names. The first step's
    // parameters are the LLM's input (and live in the order
    // the user wrote them). Any extra parameter names that
    // appear in later steps' parameter lists (positions
    // 1..end) are appended in the order they first appear.
    //
    // We preserve the *type* of the first occurrence of each
    // name. A duplicate name with a different type is a
    // compile error in the user's source code (the `#[tool]`
    // codegen would already flag it via `validate_impl`); the
    // macro does not re-check.
    let mut all_params: Vec<(Ident, Type)> = first_step
        .param_names
        .iter()
        .cloned()
        .zip(first_step.param_types.iter().cloned())
        .collect();
    for step in steps.iter().skip(1) {
        for (name, ty) in step
            .param_names
            .iter()
            .skip(1)
            .zip(step.param_types.iter().skip(1))
        {
            if !all_params.iter().any(|(n, _)| n == name) {
                all_params.push((name.clone(), ty.clone()));
            }
        }
    }

    let param_decls: Vec<TokenStream2> = all_params
        .iter()
        .map(|(name, ty)| {
            quote! { #name: #ty }
        })
        .collect();

    let return_ty = &last_step.return_type;

    // Generate the body: call each step in order, threading
    // output to input. The first step receives the LLM's
    // arguments directly; every subsequent step receives the
    // previous step's return value as its first argument plus
    // its *own* pass-through arguments (i.e. its parameter
    // names from index 1 onwards, which the user named in
    // the original method signature).
    //
    // Why use the *current* step's pass-through names (not
    // the first step's)? Each step's parameter list is
    // user-authored; the names are part of the signature.
    // For a chain like
    //
    //     fn search_flights(&self, origin: String, dest: String) -> ...
    //     fn filter_by_price(&self, flights: Vec<Flight>, max_price: f64) -> ...
    //     fn book_flight(&self, flights: Vec<Flight>) -> ...
    //
    // the call sites are:
    //
    //     self.search_flights(origin, dest)
    //     self.filter_by_price(<prev>, max_price)
    //     self.book_flight(<prev>)
    //
    // i.e. the names come from the step being called, not
    // from the first step. The macro threads the previous
    // return value as the first argument and forwards the
    // rest of the current step's parameters (which are
    // already in scope as method parameters of the synthetic
    // method when the names match, or as forwarders when
    // they don't).
    //
    // The synthetic method's parameter list (built above)
    // takes the *union* of the first step's parameters and
    // any extra parameters added by later steps. This means
    // the names in the synthetic method's signature are
    // exactly the names of the first step's parameters,
    // plus any extras from later steps. For a uniform
    // pipeline, the names match step-by-step. For
    // heterogeneous pipelines, the synthetic method exposes
    // the union, and the call site uses the current step's
    // own names.
    let mut body_stmts: Vec<TokenStream2> = Vec::new();
    for (i, step) in steps.iter().enumerate() {
        let step_ident = &step.ident;
        let result_ident = format_ident!("__compose_step_{}_result", i);
        let call_args: TokenStream2 = if i == 0 {
            // First step: the LLM's arguments map directly to
            // the first step's parameter list.
            let names = &first_step.param_names;
            quote! { #(#names),* }
        } else {
            // Subsequent steps: the previous step's return
            // value replaces the first argument; the rest of
            // the current step's parameter names (from index
            // 1) are forwarded unchanged.
            let prev_result = format_ident!("__compose_step_{}_result", i - 1);
            let pass_through: Vec<_> = step.param_names.iter().skip(1).collect();
            quote! { #prev_result, #(#pass_through),* }
        };
        body_stmts.push(quote! {
            let #result_ident = self.#step_ident(#call_args);
        });
    }
    // The composed tool's return value is the last step's
    // result (already bound to `__compose_step_{N-1}_result`).
    let last_idx = steps.len() - 1;
    let last_result = format_ident!("__compose_step_{}_result", last_idx);
    body_stmts.push(quote! { #last_result });

    let body = body_stmts;

    // The synthetic method's identifier is the composed
    // tool's name. The macro takes a `name: String` from
    // `#[compose(name = "...")]`; we convert to an `Ident`
    // here so the `parse_quote!` interpolator sees an
    // identifier (not a string literal). The composed name
    // is constrained to be a valid Rust ident by `ComposeAttrs`
    // (it is also a valid JSON-Schema identifier per
    // tokitai's tool-name rule).
    let composed_ident = syn::Ident::new(name, proc_macro2::Span::call_site());

    syn::parse_quote! {
        /// Composed tool entry point. The body is generated by
        /// `#[compose]`; do not call this method directly. The
        /// LLM-facing dispatcher routes the call through
        /// `__call_<name>` which threads the LLM's arguments
        /// through the named sub-methods in order.
        #[doc = ""]
        #[doc = "T-017: synthetic method; safe to ignore in IDE go-to-definition."]
        #[allow(dead_code)]
        pub fn #composed_ident(&self, #(#param_decls),*) -> #return_ty {
            #(#body)*
        }
    }
}

/// Top-level entry point for the `#[compose]` proc-macro
/// attribute. See the module-level documentation for the design.
pub fn expand(attr: TokenStream, item: TokenStream) -> TokenStream {
    // Convert the `proc_macro::TokenStream` inputs to
    // `proc_macro2::TokenStream` so the `syn` parsers (which
    // expect `proc_macro2::TokenStream`) can consume them.
    // The two types are distinct even though they have the
    // same name; the conversion is a thin newtype wrap.
    let attr_ts: TokenStream2 = attr.into();
    let item_ts: TokenStream2 = item.into();

    // Parse the `#[compose(...)]` attribute body. The
    // `Parse` impl on `ComposeAttrs` accepts the
    // `name = "..."` and `steps = [...]` keys.
    let attrs = match syn::parse2::<ComposeAttrs>(attr_ts) {
        Ok(a) => a,
        Err(e) => {
            return e.to_compile_error().into();
        }
    };

    // Parse the annotated item as an `impl` block. Anything
    // else is a user error — `#[compose]` is only valid on
    // `impl` blocks (we surface a clear error anchored at the
    // item's span).
    let mut impl_item: ItemImpl = match syn::parse2(item_ts) {
        Ok(impl_item) => impl_item,
        Err(_) => {
            return MacroError::new(
                crate::error::ErrorCode::E0019,
                proc_macro2::Span::call_site(),
                "`#[compose]` must be applied to an `impl` block, not a free item",
            )
            .with_help(
                "place `#[compose]` directly above an `impl Foo { ... }` block; \
                 the attribute looks up the named steps on that impl's method list",
            )
            .to_compile_error()
            .into();
        }
    };

    // 1. Resolve every named step to a `StepInfo` (or accumulate
    //    a diagnostic per failing step). We resolve all steps
    //    first so a single failure on step N does not mask
    //    failures on later steps.
    let mut step_infos: Vec<StepInfo> = Vec::with_capacity(attrs.steps.len());
    let mut errors: Vec<MacroError> = Vec::new();
    for ident in &attrs.steps {
        match resolve_step(ident, &impl_item) {
            Ok(info) => step_infos.push(info),
            Err(err) => errors.push(err),
        }
    }

    // 2. Run the chain-level checks (acyclicity, type chain,
    //    step count). These checks need every step to have
    //    resolved cleanly; if any resolution failed we skip
    //    the chain checks to avoid cascading errors. The user
    //    fixes the resolution problem first, then sees the
    //    chain problem.
    if errors.is_empty() {
        errors.extend(validate_chain(&step_infos, &attrs));
    }

    if !errors.is_empty() {
        // Emit the impl block unchanged (so subsequent
        // unrelated errors do not pile on) plus the
        // collected `compile_error!` invocations.
        let mut tokens = TokenStream2::new();
        for err in &errors {
            tokens.extend(err.to_compile_error());
        }
        return quote! {
            #impl_item
            #tokens
        }
        .into();
    }

    // 3. Build the synthetic method that the `#[tool]`
    //    codegen will pick up. The synthetic method's name
    //    is the composed tool's name; the codegen's regular
    //    `__call_<name>` machinery wraps it for the LLM.
    let first_step = &step_infos[0];
    let last_step = &step_infos.last().expect("validate_chain ensures len >= 2");
    let synthetic = build_synthetic_method(&attrs.name, first_step, last_step, &step_infos);

    // 4. Inject the synthetic method into the impl block. The
    //    `#[tool]` codegen (which is invoked separately, or in
    //    the same pass when the user stacked `#[tool]` and
    //    `#[compose]`) will collect the synthetic method via
    //    its regular `collect_tool_methods` pass and register
    //    it as one tool entry.
    //
    //    We also tag the synthetic method with a `#[doc = "..."]`
    //    block that includes the user-supplied composition
    //    description (T-017: the description is a fixed string
    //    of the form `"Composed: a -> b -> c"`). The codegen
    //    picks up the doc comment as the tool's description.
    let synthetic_doc = format!(
        "Composed tool (T-017): chains [{}] in sequence. \
         The LLM calls this as a single tool; the wrapper runs each step in process.",
        attrs
            .steps
            .iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>()
            .join(" -> ")
    );
    let mut synthetic = synthetic;
    let doc_attr: Attribute = syn::parse_quote! {
        #[doc = #synthetic_doc]
    };
    synthetic.attrs.insert(0, doc_attr);
    impl_item.items.push(ImplItem::Fn(synthetic));

    // 5. Strip the `#[compose(...)]` attribute from the impl
    //    block so the codegen does not try to re-parse it
    //    later. The `#[tool]` attribute (if any) is left
    //    untouched.
    impl_item.attrs.retain(|attr| {
        if attr.path().is_ident("compose") {
            return false;
        }
        true
    });

    quote! { #impl_item }.into()
}
